# Generated by Django 3.0.4 on 2020-03-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycbg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolelists',
            options={'verbose_name': '角色列表', 'verbose_name_plural': 'verbose_name'},
        ),
        migrations.AlterModelOptions(
            name='specialrecommend',
            options={'verbose_name': '专题推荐', 'verbose_name_plural': 'verbose_name'},
        ),
        migrations.AlterModelOptions(
            name='worthwatching',
            options={'verbose_name': '值得看', 'verbose_name_plural': 'verbose_name'},
        ),
        migrations.AlterModelTable(
            name='rolelists',
            table='角色表',
        ),
        migrations.AlterModelTable(
            name='specialrecommend',
            table='专题分类',
        ),
        migrations.AlterModelTable(
            name='worthwatching',
            table='推荐视频',
        ),
    ]
